#Get the list of categories
GET http://localhost:5084/categories
###

#Get an specific category
GET http://localhost:5084/categories/5
###

POST http://localhost:5084/categories
Content-Type: application/json

{
    "Name": "Chocolatitos"
}

###
PUT http://localhost:5084/categories/7
Content-Type: application/json

{
    "Name": "Chocolatitos"
}

###
DELETE http://localhost:5084/categories/7
Content-Type: application/json
