#Get the list of transactions
GET http://localhost:5084/foods
###

#Get an specific transactions
GET http://localhost:5084/foods/1
###

//Insert transactions
POST http://localhost:5084/foods
Content-Type: application/json

{
    "Name": "Chocolatito",
    "Brand": "Nestle",
    "CategoryID": 8
}

###
PUT http://localhost:5084/foods/2
Content-Type: application/json

{
    "Name": "Broccoli",
    "Brand": "Local",
    "CategoryID": 3
}

###
DELETE http://localhost:5084/foods/1
Content-Type: application/json
